apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimeStamp: null
  labels:
    app: ngdep
  name: ngdep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngdep
  strategy: {}
  template:
    metadata:
      creationTimeStamp: null
      labels:
        app: ngdep
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}